// <auto-generated />
namespace QuanLyThuChi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_refrerence : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_refrerence));
        
        string IMigrationMetadata.Id
        {
            get { return "201508110801159_alter_refrerence"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
