// <auto-generated />
namespace QuanLyThuChi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_thuchi_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_thuchi_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "201508140333035_alter_thuchi_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
